django:
  build: .
  command: "sh deploy.sh"
  environment:
    RUN_ENV: "$RUN_ENV"
    EQ_SENTRY_DNS: "$EQ_SENTRY_DNS"
    EQ_SMTP_USER: "$EQ_SMTP_USER"
    EQ_SMTP_PASS: "$EQ_SMTP_PASS"
    DBBACKUP_TOKENS_FILEPATH: "$DBBACKUP_TOKENS_FILEPATH"
    DBBACKUP_DROPBOX_APP_KEY: "$DBBACKUP_DROPBOX_APP_KEY"
    DBBACKUP_DROPBOX_APP_SECRET: "$DBBACKUP_DROPBOX_APP_SECRET"
    GOOGLE_ANALYTICS_ID: "$GOOGLE_ANALYTICS_ID"
  ports:
   - "8080:8000"
   - "5555:5555"
  volumes:
   - .:/project
  links:
   - redis
   - postgres
   - memcached
redis:
  image: redis:latest
  command: redis-server --appendonly yes

postgres:
  image: postgres:9.4
  volumes:
    - eq_postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: "eq_database"
    POSTGRES_USER: "eq_database"

memcached:
  image: memcached
  command: memcached -I 15m
