django:
  build: .
  command: "sh deploy.sh"
  environment:
    RUN_ENV: "$RUN_ENV"
    SCHEDUL_SENTRY_URL: "$EQ_SENTRY_URL"
    EQ_SMTP_USER: "$EQ_SMTP_USER"
    EQ_SMTP_PASS: "$EQ_SMTP_PASS"
  ports:
   - "80:8000"
   - "5555:5555"
  volumes:
   - .:/project
  links:
   - redis
   - postgres
redis:
  image: redis:latest
  command: redis-server --appendonly yes

postgres:
  image: postgres:9.4
  volumes:
    - eq_postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: "eq_database"
    POSTGRES_USER: "eq_database"
